name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"

      - name: Build docker image
        run: docker build -t demododev/dockerghtest:latest .

      - name: Tag docker image
        run: docker tag demododev/dockerghtest:latest demododev/dockerghtest-${{ github.sha }}:latest

      - name: Push docker image
        run: docker push demododev/dockerghtest-${{ github.sha }}:latest